#!/bin/bash -e

PAC=_PACKAGE_
USER=_USER_
GROUP=_GROUP_
HOST=$(hostname -f)

variant=base
if [ "$1" == "configure" ] ; then

    # Source debconf library.
    . /usr/share/debconf/confmodule

    mkdir -p /var/log/fs-rec-api
    mkdir -p /var/log/record

    chmod 777 /var/log/record

 	systemctl enable $PAC
 	systemctl start $PAC

fi

exit 0
